# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: vaat

# The runtime the application uses.
type: "php:7.4"

timezone: Europe/Zurich

# The size of the persistent disk of the application (in MB).
disk: 256

# Configuration of the build of the application.
build:
    flavor: none

dependencies:
    nodejs:
      gulp: "4.0.2"
      yarn: "1.22.5"

hooks:
    build: |
        set -e
        yarn install
        gulp

# The configuration of app when it is exposed to the web.
web:
    locations:
        "/":
            "root": "public"
            index:
              - "index.php"
            # The number of seconds whitelisted (static) content should be cached.
            expires: -1
            scripts: true
            allow: true
            rules:
                \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|html|ico|svg?)$:
                    allow: true

# trigger deploy