"https://{default}/":
    type: upstream
    upstream: "web:http"
    cache:
        enabled: false
    tls:
        strict_transport_security:
            enabled: true
            include_subdomains: true
            preload: true

http://{default}/:
    type: redirect
    to: "https://{default}/"

"https://www.vaat.ee/":
    type: redirect
    to: "https://{default}/"

"https://vaat.ch/":
    type: upstream
    upstream: "web:http"
    cache:
        enabled: false
    tls:
        strict_transport_security:
            enabled: true
            include_subdomains: true
            preload: true

"https://www.vaat.ch/":
    type: redirect
    to: "https://vaat.ch/"