"https://vaat.ee/":
    type: upstream
    upstream: "web:http"
    cache:
        enabled: false

"https://www.vaat.ee/":
    type: redirect
    to: "https://vaat.ee/"

"https://vaat.ch/":
    type: upstream
    upstream: "web:http"
    cache:
        enabled: false

"https://www.vaat.ch/":
    type: redirect
    to: "https://vaat.ch/"

http://{default}/:
    type: redirect
    to: "https://{default}/"

https://dashboard.vaat.ee/:
    type: upstream
    upstream: "dashboard:http"
    cache:
        enabled: false
