"https://vaat.ee/":
    type: upstream
    upstream: "web:http"
    cache:
        enabled: false

"https://www.vaat.ee/":
    type: redirect
    to: "https://vaat.ee/"
    cache:
        enabled: false

"https://vaat.ch/":
    type: upstream
    upstream: "web:http"
    cache:
        enabled: false

"https://www.vaat.ch/":
    type: redirect
    to: "https://vaat.ch/"
    cache:
        enabled: false

http://{default}/:
    type: redirect
    to: "https://{default}/"
    cache:
        enabled: false

https://dashboard.vaat.ee/:
    type: upstream
    upstream: "dashboard:http"
    cache:
        enabled: false
